import { computeReminderDate } from '@/src/utils/dates';

export type FoodType = 'dairy' | 'meat' | 'fish' | 'vegetables' | 'unknown';

export const FOOD_TYPES: FoodType[] = [
  'dairy',
  'meat',
  'fish',
  'vegetables',
  'unknown',
];

/** Days before expiry used when filling a new inventory item. */
export const DAYS_BEFORE_BY_FOOD_TYPE: Record<FoodType, number> = {
  dairy: 3,
  meat: 1,
  fish: 1,
  vegetables: 2,
  unknown: 1,
};

export const FOOD_TYPE_LABEL_KEYS = {
  dairy: 'foodTypeDairy',
  meat: 'foodTypeMeat',
  fish: 'foodTypeFish',
  vegetables: 'foodTypeVegetables',
  unknown: 'foodTypeUnknown',
} as const;

export function daysBeforeExpiryForFoodType(
  type: FoodType,
  daysByType: Record<FoodType, number> = DAYS_BEFORE_BY_FOOD_TYPE,
): number {
  const days = daysByType[type];
  if (typeof days !== 'number' || !Number.isFinite(days)) {
    return DAYS_BEFORE_BY_FOOD_TYPE[type];
  }
  return Math.max(0, days);
}

export function reminderDateForFoodType(
  expirationISO: string,
  type: FoodType,
  daysByType: Record<FoodType, number> = DAYS_BEFORE_BY_FOOD_TYPE,
): string {
  return computeReminderDate(
    expirationISO,
    daysBeforeExpiryForFoodType(type, daysByType),
  );
}

const KEYWORDS: Record<Exclude<FoodType, 'unknown'>, string[]> = {
  fish: [
    'fish',
    'salmon',
    'tuna',
    'cod',
    'trout',
    'shrimp',
    'prawn',
    'prawns',
    'seafood',
    'herring',
    'sardine',
    'sardines',
    'mackerel',
    'anchovy',
    'anchovies',
    'haddock',
    'halibut',
    'swordfish',
    'bass',
    'tilapia',
    'crab',
    'lobster',
    'mussel',
    'mussels',
    'oyster',
    'oysters',
    'clam',
    'clams',
    'squid',
    'octopus',
    'scallop',
    'scallops',
    'pescado',
    'peix',
    'peixe',
    'fisch',
    'poisson',
    'pesce',
    'vis',
    'kala',
    'fisk',
    'hal',
    'balik',
    'ryba',
    'лосось',
    'тунец',
    'креветка',
    'рыба',
    'ψάρι',
    'σολομός',
    'τόνος',
    'γαρίδα',
    'سمك',
    'سلمون',
    'تونة',
    'جمبري',
    '鱼',
    '鮭魚',
    '鲑鱼',
    '三文鱼',
    '金枪鱼',
    '蝦',
    '虾',
    '魚',
    'サーモン',
    'マグロ',
    'エビ',
    '생선',
    '연어',
    '참치',
    '새우',
    'atun',
    'atún',
    'atum',
    'tonyina',
    'thunfisch',
    'thon',
    'tonno',
    'tonijn',
    'tonnikala',
    'tonfisk',
    'tun',
    'tonhal',
    'tuńczyk',
    'salmao',
    'salmão',
    'saumon',
    'salmone',
    'zalm',
    'lohi',
    'lax',
    'laks',
    'lazac',
    'somon',
    'łosoś',
    'gamba',
    'gambas',
    'camarao',
    'camarão',
    'marisco',
    'mariscos',
    'merluza',
    'bacalao',
    'bacalao',
    'bacalhau',
    'garnelen',
    'kabeljau',
    'crevette',
    'crevettes',
    'fruits de mer',
    'cabillaud',
    'gambero',
    'gamberi',
    'frutti di mare',
    'merluzzo',
    'garnaal',
    'garnalen',
    'katkarapu',
    'rakor',
    'räkor',
    'rejer',
    'karides',
    'krewetka',
  ],
  meat: [
    'meat',
    'beef',
    'pork',
    'chicken',
    'turkey',
    'lamb',
    'ham',
    'bacon',
    'sausage',
    'sausages',
    'steak',
    'mince',
    'minced',
    'veal',
    'duck',
    'goose',
    'salami',
    'chorizo',
    'pepperoni',
    'burger',
    'burgers',
    'hot dog',
    'hotdog',
    'wurst',
    'schnitzel',
    'meatball',
    'meatballs',
    'liver',
    'ribs',
    'carne',
    'ternera',
    'cerdo',
    'pollo',
    'pavo',
    'jamon',
    'jamón',
    'salchicha',
    'bistec',
    'cordero',
    'carn',
    'vedella',
    'porc',
    'pollastre',
    'pernil',
    'frango',
    'peru',
    'presunto',
    'fleisch',
    'rind',
    'schwein',
    'huhn',
    'hühner',
    'pute',
    'schinken',
    'speck',
    'lamm',
    'viande',
    'boeuf',
    'bœuf',
    'poulet',
    'dinde',
    'jambon',
    'saucisse',
    'agneau',
    'manzo',
    'maiale',
    'tacchino',
    'prosciutto',
    'salsiccia',
    'agnello',
    'vlees',
    'rund',
    'varkensvlees',
    'kip',
    'kalkoen',
    'spek',
    'worst',
    'liha',
    'kana',
    'kinkku',
    'kott',
    'kött',
    'kyckling',
    'skinka',
    'kod',
    'kød',
    'kylling',
    'hus',
    'hús',
    'csirke',
    'sonka',
    'tavuk',
    'sucuk',
    'köfte',
    'mięso',
    'wołowina',
    'wieprzowina',
    'kurczak',
    'szynka',
    'мясо',
    'говядина',
    'свинина',
    'курица',
    'ветчина',
    'κρέας',
    'μοσχάρι',
    'χοιρινό',
    'κοτόπουλο',
    'ζαμπόν',
    'لحم',
    'بقري',
    'دجاج',
    'نقانق',
    '肉',
    '牛肉',
    '豬肉',
    '猪肉',
    '雞肉',
    '鸡肉',
    '火腿',
    '香腸',
    '香肠',
    'ハム',
    'ソーセージ',
    '鶏肉',
    '豚肉',
    '고기',
    '소고기',
    '돼지고기',
    '닭고기',
    '햄',
    '소시지',
  ],
  dairy: [
    'dairy',
    'milk',
    'yogurt',
    'yoghurt',
    'yogourt',
    'cheese',
    'butter',
    'cream',
    'kefir',
    'quark',
    'cottage',
    'mozzarella',
    'cheddar',
    'parmesan',
    'gouda',
    'brie',
    'feta',
    'ricotta',
    'cream cheese',
    'sour cream',
    'ice cream',
    'buttermilk',
    'ghee',
    'paneer',
    'fromage',
    'lacteo',
    'lácteo',
    'leche',
    'yogur',
    'queso',
    'mantequilla',
    'nata',
    'crema',
    'lactic',
    'làctic',
    'llet',
    'iogurt',
    'formatge',
    'mantega',
    'leite',
    'iogurte',
    'queijo',
    'manteiga',
    'milch',
    'joghurt',
    'kase',
    'käse',
    'sahne',
    'molkerei',
    'lait',
    'yaourt',
    'beurre',
    'creme',
    'crème',
    'latte',
    'formaggio',
    'burro',
    'panna',
    'zuivel',
    'melk',
    'kaas',
    'boter',
    'room',
    'maito',
    'jogurtti',
    'juusto',
    'voi',
    'kerma',
    'mejeri',
    'mjolk',
    'mjölk',
    'ost',
    'smor',
    'smör',
    'gradde',
    'grädde',
    'maelk',
    'mælk',
    'flode',
    'fløde',
    'tej',
    'sajt',
    'vaj',
    'tejfol',
    'tejföl',
    'sut',
    'süt',
    'peynir',
    'tereyagi',
    'tereyağı',
    'nabial',
    'nabiał',
    'mleko',
    'jogurt',
    'ser',
    'maslo',
    'masło',
    'smietana',
    'śmietana',
    'молоко',
    'йогурт',
    'сыр',
    'масло',
    'сливки',
    'творог',
    'γάλα',
    'γιαούρτι',
    'τυρί',
    'βούτυρο',
    'κρέμα',
    'حليب',
    'زبادي',
    'جبن',
    'زبدة',
    'قشدة',
    '奶',
    '牛奶',
    '酸奶',
    '奶酪',
    '芝士',
    '黄油',
    '奶油',
    '牛乳',
    'ミルク',
    'ヨーグルト',
    'チーズ',
    'バター',
    '生クリーム',
    '우유',
    '요거트',
    '요구르트',
    '치즈',
    '버터',
    '크림',
  ],
  vegetables: [
    'vegetable',
    'vegetables',
    'veggie',
    'veggies',
    'salad',
    'lettuce',
    'spinach',
    'kale',
    'cabbage',
    'broccoli',
    'cauliflower',
    'carrot',
    'carrots',
    'tomato',
    'tomatoes',
    'cucumber',
    'pepper',
    'peppers',
    'zucchini',
    'courgette',
    'eggplant',
    'aubergine',
    'onion',
    'onions',
    'garlic',
    'potato',
    'potatoes',
    'celery',
    'asparagus',
    'bean',
    'beans',
    'peas',
    'corn',
    'mushroom',
    'mushrooms',
    'avocado',
    'pumpkin',
    'squash',
    'leek',
    'leeks',
    'radish',
    'beet',
    'beetroot',
    'turnip',
    'artichoke',
    'fennel',
    'arugula',
    'rocket',
    'chard',
    'bok choy',
    'greens',
    'verdura',
    'verduras',
    'vegetal',
    'ensalada',
    'lechuga',
    'espinaca',
    'brocoli',
    'brócoli',
    'zanahoria',
    'tomate',
    'pepino',
    'pimiento',
    'calabacin',
    'calabacín',
    'berenjena',
    'cebolla',
    'ajo',
    'patata',
    'papa',
    'apio',
    'esparrago',
    'espárrago',
    'judia',
    'judía',
    'guisante',
    'maiz',
    'maíz',
    'champinon',
    'champiñón',
    'aguacate',
    'calabaza',
    'amanida',
    'enciam',
    'espinacs',
    'col',
    'pastanaga',
    'tomaquet',
    'cogombre',
    'pebrot',
    'ceba',
    'legumes',
    'alface',
    'espinafre',
    'couve',
    'brocolis',
    'brócolis',
    'cenoura',
    'pimentao',
    'pimentão',
    'abobrinha',
    'berinjela',
    'cebola',
    'alho',
    'batata',
    'gemuse',
    'gemüse',
    'salat',
    'spinat',
    'kohl',
    'brokkoli',
    'karotte',
    'mohre',
    'möhre',
    'gurke',
    'paprika',
    'zwiebel',
    'knoblauch',
    'kartoffel',
    'sellerie',
    'spargel',
    'bohne',
    'erbse',
    'mais',
    'pilz',
    'kurbis',
    'kürbis',
    'legume',
    'laitue',
    'epinard',
    'épinard',
    'chou',
    'carotte',
    'concombre',
    'poivron',
    'oignon',
    'ail',
    'pomme de terre',
    'celeri',
    'céleri',
    'asperge',
    'haricot',
    'petit pois',
    'champignon',
    'avocat',
    'courge',
    'insalata',
    'lattuga',
    'spinaci',
    'cavolo',
    'carota',
    'pomodoro',
    'cetriolo',
    'peperone',
    'zucchina',
    'melanzana',
    'cipolla',
    'aglio',
    'sedano',
    'asparago',
    'fagiolo',
    'pisello',
    'fungo',
    'zucca',
    'groente',
    'groenten',
    'sla',
    'spinazie',
    'kool',
    'wortel',
    'komkommer',
    'paprika',
    'courgette',
    'ui',
    'knoflook',
    'aardappel',
    'kasvis',
    'vihannes',
    'salaatti',
    'pinaatti',
    'kaali',
    'porkkana',
    'tomaatti',
    'kurkku',
    'paprika',
    'sipuli',
    'valkosipuli',
    'peruna',
    'gronsak',
    'grönsak',
    'sallad',
    'spenat',
    'kål',
    'morot',
    'gurka',
    'lök',
    'potatis',
    'grontsag',
    'grøntsag',
    'salat',
    'spinat',
    'gulerod',
    'agurk',
    'løg',
    'kartoffel',
    'zoldseg',
    'zöldség',
    'salata',
    'spenót',
    'káposzta',
    'répa',
    'paradicsom',
    'uborka',
    'hagyma',
    'burgonya',
    'sebze',
    'salata',
    'ıspanak',
    'lahana',
    'havuç',
    'domates',
    'salatalık',
    'biber',
    'soğan',
    'sarımsak',
    'patates',
    'warzywa',
    'sałata',
    'szpinak',
    'kapusta',
    'marchew',
    'pomidor',
    'ogórek',
    'papryka',
    'cebula',
    'czosnek',
    'ziemniak',
    'овощи',
    'салат',
    'шпинат',
    'капуста',
    'морковь',
    'помидор',
    'огурец',
    'перец',
    'лук',
    'чеснок',
    'картофель',
    'λαχανικά',
    'σαλάτα',
    'σπανάκι',
    'λάχανο',
    'καρότο',
    'ντομάτα',
    'αγγούρι',
    'πιπεριά',
    'κρεμμύδι',
    'σκόρδο',
    'πατάτα',
    'خضار',
    'خضروات',
    'سلطة',
    'خس',
    'سبانخ',
    'ملفوف',
    'جزر',
    'طماطم',
    'خيار',
    'فلفل',
    'بصل',
    'ثوم',
    'بطاطس',
    '蔬菜',
    '沙拉',
    '生菜',
    '菠菜',
    '卷心菜',
    '西兰花',
    '胡萝卜',
    '番茄',
    '黄瓜',
    '辣椒',
    '洋葱',
    '大蒜',
    '土豆',
    '野菜',
    'サラダ',
    'レタス',
    'ほうれん草',
    'キャベツ',
    'ブロッコリー',
    'にんじん',
    'トマト',
    'きゅうり',
    'ピーマン',
    'たまねぎ',
    'にんにく',
    'じゃがいも',
    '채소',
    '야채',
    '샐러드',
    '상추',
    '시금치',
    '양배추',
    '브로콜리',
    '당근',
    '토마토',
    '오이',
    '고추',
    '양파',
    '마늘',
    '감자',
  ],
};

const DETECT_ORDER: Exclude<FoodType, 'unknown'>[] = [
  'fish',
  'meat',
  'dairy',
  'vegetables',
];

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '');
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function hasKeyword(haystack: string, keyword: string): boolean {
  const k = normalize(keyword);
  if (!k) return false;
  if (/[\u0400-\u04FF\u0600-\u06FF\u0370-\u03FF\u3040-\u30FF\u4E00-\u9FFF\uAC00-\uD7AF]/.test(k)) {
    return haystack.includes(k);
  }
  const escaped = escapeRegExp(k);
  return new RegExp(`(^|[^\\p{L}\\p{N}])${escaped}([^\\p{L}\\p{N}]|$)`, 'u').test(
    haystack,
  );
}

export function inferFoodType(
  name: string,
  extraText = '',
): FoodType {
  const haystack = normalize(`${name} ${extraText}`.trim());
  if (!haystack) return 'unknown';

  for (const type of DETECT_ORDER) {
    if (KEYWORDS[type].some((keyword) => hasKeyword(haystack, keyword))) {
      return type;
    }
  }
  return 'unknown';
}
