#!/bin/bash
# Xcode Cloud still points at ios/NoWaste.xcworkspace (the old app name).
# ios/ is generated by Expo and not committed, so this script recreates the
# native project after clone and aliases it to the name Apple expects.
set -euo pipefail

echo "ci_post_clone.sh: generating native iOS project for Xcode Cloud"

ROOT="${CI_PRIMARY_REPOSITORY_PATH:-}"
if [ -z "$ROOT" ]; then
  ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
fi
cd "$ROOT"

export LANG="${LANG:-en_US.UTF-8}"
export LC_ALL="${LC_ALL:-en_US.UTF-8}"
# Xcode Cloud sets CI=TRUE; getenv only accepts lowercase true/false.
export CI=true
export EXPO_NO_TELEMETRY=1

TMP="$(mktemp -d)"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT

if [ -d ios/ci_scripts ]; then
  cp -R ios/ci_scripts "$TMP/ci_scripts"
fi

if ! command -v node >/dev/null 2>&1; then
  brew install node
fi
if ! command -v pod >/dev/null 2>&1; then
  brew install cocoapods
fi

rm -rf ios

if [ -f package-lock.json ]; then
  npm ci
else
  npm install
fi

npx expo prebuild --platform ios --non-interactive

if [ -d "$TMP/ci_scripts" ]; then
  cp -R "$TMP/ci_scripts" ios/ci_scripts
fi

shopt -s nullglob
GENERATED_WS=""
for ws in ios/*.xcworkspace; do
  if [ "$(basename "$ws")" != "NoWaste.xcworkspace" ]; then
    GENERATED_WS="$ws"
    break
  fi
done

if [ -n "$GENERATED_WS" ]; then
  rm -rf ios/NoWaste.xcworkspace
  cp -R "$GENERATED_WS" ios/NoWaste.xcworkspace
  echo "Aliased $GENERATED_WS -> ios/NoWaste.xcworkspace"
fi

for scheme_dir in ios/*.xcodeproj/xcshareddata/xcschemes; do
  [ -d "$scheme_dir" ] || continue
  if [ ! -f "$scheme_dir/NoWaste.xcscheme" ]; then
    for src in "$scheme_dir"/*.xcscheme; do
      cp "$src" "$scheme_dir/NoWaste.xcscheme"
      echo "Aliased scheme $(basename "$src") -> NoWaste.xcscheme"
      break
    done
  fi
done

echo "ci_post_clone.sh: done"
